# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2d16adb21581b27c8b894003167c572af589ec521d8a57121eae568f454fe8ececbbbc8f1e05189180e3b2234ec7beb2cfeffdb2987303b94d7f95478d459ab1

test:
  secret_key_base: 8724c2714669f774be66616d5a88a450b9e32cbb11a9d8cb8e6728c13b89ec40e0fbc2d4aa8f5f80d7664ff95f601935d3a7f297c00156961c8901528bff4966

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
